// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[id].ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_create from "./routes/api/create.ts";
import * as $index from "./routes/index.tsx";
import * as $Welcome from "./islands/Welcome.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id].ts": $_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/create.ts": $api_create,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Welcome.tsx": $Welcome,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
